// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Add web configuration
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyA7cJZp1DgbbOeZcCWzuiFV7FdNBjeJr2Y",
    authDomain: "judging-app-749b1.firebaseapp.com",
    databaseURL:
        "https://judging-app-749b1-default-rtdb.asia-southeast1.firebasedatabase.app",
    projectId: "judging-app-749b1",
    storageBucket: "judging-app-749b1.firebasestorage.app",
    messagingSenderId: "249570305920",
    appId: "1:249570305920:web:84f3cad1d9b133613d8365",
    measurementId: "G-2GEFSHHN6S",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz8cE9uLls6lYXdT5EJX1B4AA7grSB4vU',
    appId: '1:249570305920:android:9d77851d27bf10113d8365',
    messagingSenderId: '249570305920',
    projectId: 'judging-app-749b1',
    databaseURL:
        'https://judging-app-749b1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'judging-app-749b1.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7cJZp1DgbbOeZcCWzuiFV7FdNBjeJr2Y',
    appId: '1:249570305920:web:b1d26b62707638ac3d8365',
    messagingSenderId: '249570305920',
    projectId: 'judging-app-749b1',
    authDomain: 'judging-app-749b1.firebaseapp.com',
    databaseURL:
        'https://judging-app-749b1-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'judging-app-749b1.firebasestorage.app',
    measurementId: 'G-X1Y14GDHL5',
  );
}
